"""
DOCUMENTATION WRITER AGENT
-----------------------------
Purpose: write a concise incident narrative displayed in the Full Report section.

The report is stored in workflow state and persisted by main.py. Downloadable
PDF, Markdown, and text reports are generated by report_export.py from stored data.
"""

import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from state import IncidentState
from utils.llm_helper import invoke_with_retry
from utils.report_export import _clean_text

load_dotenv()

llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0,
    max_tokens=2048,
    reasoning_effort="low",
    api_key=os.getenv("GROQ_API_KEY")
)


def report_writer_agent(state: IncidentState) -> IncidentState:
    # This narrative is for human readers; downloadable reports use the same
    # stored facts through utils.report_export.py.
    print("\n[DOCUMENTATION WRITER AGENT] Writing the incident report...")

    prompt = f"""You are a technical writer creating an incident post-mortem report for a DevOps team.

Here is all the information about this incident:
- Original log: "{state['raw_log']}"
- Anomaly detected: {state['is_anomaly']}
- Anomaly reason: "{state['anomaly_reason']}"
- Root cause: "{state['root_cause']}"
- Root cause confidence: {state['root_cause_confidence']}
- Suggested fix: "{state['suggested_fix']}"
- Fix confidence: {state['fix_confidence']}
- Needs human review: {state['needs_human_review']}

Write a clean, professional incident report with these sections:
1. Summary
2. Root Cause
3. Recommended Fix
4. Confidence & Review Status

STRICT RULES:
- Use ONLY the facts provided above. Do NOT invent incident IDs, dates, times,
  durations, customer impact numbers, team names, or people.
- The fix is a RECOMMENDATION only. Do NOT say it was applied, that the incident
  was resolved, or that any action has already been taken.
- If a detail is not provided, leave it out instead of guessing.
- Do NOT add a "prepared by" line.

Keep it concise but professional, as if it will be read by an engineering team."""

    response = invoke_with_retry(llm, prompt)
    state["final_report"] = _clean_text(response.content.strip())

    print("[DOCUMENTATION WRITER AGENT] Report ready for database storage")

    return {k: v for k, v in state.items() if k != "investigation_findings"}
